// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaFacturacion.Infrastructure.Persistence;

#nullable disable

namespace SistemaFacturacion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110024427_FixTimestampTypes")]
    partial class FixTimestampTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Correo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("direccion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("char(13)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasColumnType("char(5)")
                        .HasColumnName("tipoidentificacion");

                    b.HasKey("IdCliente");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasDatabaseName("idx_clientes_identificacion");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.ComprobanteElectronico", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcomprobante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdComprobante"));

                    b.Property<string>("ClaveAcceso")
                        .HasColumnType("char(49)")
                        .HasColumnName("claveacceso");

                    b.Property<string>("EstadoEnvio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasDefaultValue("NO_ENVIADO")
                        .HasColumnName("estadoenvio");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaautorizacion");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaenvio");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer")
                        .HasColumnName("idfactura");

                    b.Property<string>("MensajeRespuesta")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("mensajerespuesta");

                    b.Property<string>("NumeroAutorizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numeroautorizacion");

                    b.Property<string>("XmlFirmado")
                        .HasColumnType("text")
                        .HasColumnName("xmlfirmado");

                    b.Property<string>("XmlGenerado")
                        .HasColumnType("text")
                        .HasColumnName("xmlgenerado");

                    b.HasKey("IdComprobante");

                    b.HasIndex("ClaveAcceso")
                        .HasDatabaseName("idx_comprobantes_clave");

                    b.HasIndex("IdFactura")
                        .IsUnique();

                    b.ToTable("comprobanteselectronicos", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.ConfiguracionEmpresa", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idconfiguracion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<char>("Ambiente")
                        .HasColumnType("char(1)")
                        .HasColumnName("ambiente");

                    b.Property<string>("ClaveCertificado")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("clavecertificado");

                    b.Property<string>("CorreoEmpresa")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("correoempresa");

                    b.Property<string>("DireccionMatriz")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("direccionmatriz");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombrecomercial");

                    b.Property<string>("PuntoEmision")
                        .HasColumnType("char(3)")
                        .HasColumnName("puntoemision");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("razonsocial");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasColumnType("char(13)")
                        .HasColumnName("ruc");

                    b.Property<string>("RutaCertificado")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("rutacertificado");

                    b.HasKey("IdConfiguracion");

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.ToTable("configuracionempresa", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.DetalleFactura", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iddetalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdDetalle"));

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer")
                        .HasColumnName("idfactura");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("idproducto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preciounitario");

                    b.Property<decimal>("TotalLinea")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("totallinea")
                        .HasComputedColumnSql("(cantidad * preciounitario)", true);

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdProducto");

                    b.ToTable("detallefactura", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idfactura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdFactura"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaemision")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("idcliente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.Property<decimal>("Iva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("iva");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("char(17)")
                        .HasColumnName("numerofactura");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("NumeroFactura")
                        .IsUnique()
                        .HasDatabaseName("idx_facturas_numero");

                    b.ToTable("facturas", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.HistorialPrecio", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idhistorial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdHistorial"));

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacambio")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("idproducto");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.Property<string>("Motivo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("motivo");

                    b.Property<decimal?>("PrecioAnterior")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precioanterior");

                    b.Property<decimal?>("PrecioNuevo")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precionuevo");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("idx_historial_productos");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("historialprecios", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.Lote", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idlote");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdLote"));

                    b.Property<int>("CantidadActual")
                        .HasColumnType("integer")
                        .HasColumnName("cantidadactual");

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("integer")
                        .HasColumnName("cantidadinicial");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaexpiracion");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaingreso");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numerolote");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preciocompra");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("idproducto");

                    b.HasKey("IdLote");

                    b.HasIndex("NumeroLote")
                        .HasDatabaseName("idx_lotes_numero");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("idx_lotes_producto");

                    b.ToTable("lotes", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idproducto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("categoria");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precioventa");

                    b.HasKey("IdProducto");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("idx_productos_codigo");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("clavehash");

                    b.Property<string>("Correo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("correo");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nombreusuario");

                    b.Property<char>("Rol")
                        .HasColumnType("char(1)")
                        .HasColumnName("rol");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.ComprobanteElectronico", b =>
                {
                    b.HasOne("SistemaFacturacion.Domain.Entities.Factura", "Factura")
                        .WithOne("Comprobante")
                        .HasForeignKey("SistemaFacturacion.Domain.Entities.ComprobanteElectronico", "IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.DetalleFactura", b =>
                {
                    b.HasOne("SistemaFacturacion.Domain.Entities.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.Factura", b =>
                {
                    b.HasOne("SistemaFacturacion.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Facturas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.HistorialPrecio", b =>
                {
                    b.HasOne("SistemaFacturacion.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaFacturacion.Domain.Entities.Usuario", null)
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.Lote", b =>
                {
                    b.HasOne("SistemaFacturacion.Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Comprobante");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("SistemaFacturacion.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("HistorialPrecios");
                });
#pragma warning restore 612, 618
        }
    }
}
